name: Autobuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  call-prettier-workflow:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/prettier.yml

  build:
    name: Autobuild

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Get QT From Cache
        id: cache-qt
        uses: actions/cache/restore@v3
        with:
          path: C:\Qt
          key: ${{ runner.os }}-Qt563 # don't think QT version will change?

      - name: Download Qt if Needed
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          mkdir C:\Qt
          python resources\qt_download_helper.py
          cd C:\Qt
          7z x qt563.7z

      - name: Save Qt to cache
        uses: actions/cache/save@v3
        with:
          path: C:\Qt
          key: ${{ runner.os }}-Qt563 # don't think QT version will change?

      - name: Build
        run: |
          mkdir C:\spelunky2-x64dbg-plugin-autobuild
          mkdir build
          cd build
          cmake .. -DX64DBG_PLUGINS_ROOT=C:\spelunky2-x64dbg-plugin-autobuild -DQt5ROOT=C:\Qt\5.6.3\msvc2013_64\
          cmake --build . --config Release --target ALL_BUILD
          7z a ..\spelunky2-x64dbg-plugin-autobuild.zip C:\spelunky2-x64dbg-plugin-autobuild\

      - name: Create release
        if: ${{ github.event_name != 'pull_request' }}
        uses: marvinpinto/action-automatic-releases@v1.1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "autobuild"
          prerelease: true
          title: "Autobuild"
          files: |
            spelunky2-x64dbg-plugin-autobuild.zip
