name: Test Build

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Test Build

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Get QT From Cache
        id: cache-qt
        uses: actions/cache/restore@v3
        with:
          path: C:\Qt
          key: ${{ runner.os }}-Qt563 # don't think QT version will change?

      - name: Download Qt if Needed
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          mkdir C:\Qt
          python resources\qt_download_helper.py
          cd C:\Qt
          7z x qt563.7z

      - name: Save Qt to cache
        if: steps.cache-qt.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: C:\Qt
          key: ${{ runner.os }}-Qt563 # don't think QT version will change?

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DX64DBG_PLUGINS_ROOT=C:\build -DQt5ROOT=C:\Qt\5.6.3\msvc2013_64\
          cmake --build . --config Release --target ALL_BUILD
